/** 按钮图标枚举 */
export enum ButtonIconEnum {
  /** 查看更多 */
  more = 'ri:more-line',
  /** 查看详情 */
  detail = 'solar:eye-broken',
  /** 返回 */
  back = 'line-md:arrow-small-left',
  /** 分析 */
  analysis = 'tabler:analyze-filled',
  /** 编辑 */
  edit = 'line-md:edit-twotone',
  /** 删除 */
  delete = 'fluent:delete-16-filled',
  /** 设置 */
  setting = 'line-md:cog',
  /** 新增 */
  add = 'mingcute:add-fill',
  /** 刷新/同步 */
  refresh = 'solar:refresh-broken',
  /** 未收藏 */
  favorite = 'line-md:star',
  /** 已收藏 */
  favoriteFilled = 'line-md:star-filled',
  /** 链接 */
  link = 'line-md:external-link',
  /** 上升 */
  increase = 'streamline:graph-arrow-increase',
  /** 下降 */
  decrease = 'streamline:graph-arrow-decrease',
  /** 右箭头 */
  arrowRight = 'line-md:arrow-right',
  /** 完成 */
  finish = 'ep:finished',
}
